# Generated by Django 6.0.2 on 2026-04-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pain Relief', 'Pain Relief'), ('Antibiotics', 'Antibiotics'), ('Supplements', 'Supplements'), ('First Aid', 'First Aid'), ('Malaria', 'Malaria')], default='Pain Relief', max_length=50),
        ),
    ]
